### ISSUE TITLE
Support for Non-Sobol Nets

### ISSUE THREAD

**Issue by ParadaCarleton** [dmetivie/RandomizedQuasiMonteCarlo.jl#4]
Other (t, m, s) nets than Sobol nets can be useful; would you be interested in modifying this code to work with nets in general?

**Comment by ParadaCarleton** [comment]
@dmetivie [QuasiMonteCarlo.jl](https://github.com/SciML/QuasiMonteCarlo.jl/pull/45) now has support for scrambled Faure sequences. Would you be interested in merging this package into QuasiMonteCarlo.jl?

**Comment by dmetivie** [comment]
> Other (t, m, s) nets than Sobol nets can be useful; would you be interested in modifying this code to work with nets in general?

The scrambling in base 2 coded here works for generic set of points (whether they are net/sequence or neither). 
I will try to soon put an example.

I would like to add scrambling in arbitrary base `b`. 
This would nicely fit the Faure sequence you wrote [QuasiMonteCarlo.jl](https://github.com/SciML/QuasiMonteCarlo.jl/pull/45).

**Comment by dmetivie** [comment]
I updated the readme and repo (not the official version yet) for scrambling in base b. It works with your Faure sequence for Linear Matrix Scrambling and Nested Uniform Scrambling.

**Comment by ParadaCarleton** [comment]
> I updated the readme and repo (not the official version yet) for scrambling in base b. It works with your Faure sequence for Linear Matrix Scrambling and Nested Uniform Scrambling.

This is amazing, thank you so much! I've updated the Faure sequence in QMC.jl to remove randomization, so that using `InertSampler` is no longer necessary.
